version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: patronus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5433:5432'
  keycloak:
   container_name: keycloak
   image: quay.io/keycloak/keycloak:21.1.1
   environment:
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: admin
   ports:
    - "9090:8080"
   command:
    - "start-dev"
  springapp:
    container_name: patronus_app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/patronus
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      DB_HOST: db
    depends_on:
      - db
    command:
      - start
      - --auto-build
#volumes:
#  redis_vol: